(defun transf (lista)
    (setq n (length lista))
    (setq m (length (car lista)))
    (setq matrice (make-array (list n m)))
    (do ( ( i 0 (+ i 1) ) (rand lista (CDR rand) ) )
        ( (= i n ) matrice)
        (do ( (j 0 (+ j 1))  (e (CAR rand) (CDR e)) )
            ( (= j m) )
            ( setf (aref matrice i j) (CAR e) )
        )
    )
)